spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MSSQLServer;INIT=CREATE SCHEMA IF NOT EXISTS [DBO]\; SET SCHEMA [DBO];
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: DBO
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    table: schema_version
    baseline-on-migrate: true
    out-of-order: false
    locations: classpath:db/migration
    url: jdbc:h2:mem:test
    user: sa
    password: password
    schemas: DBO
server:
  servlet:
    context-path: /challenge-precios-api
    port: 8080
